# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2020.2.4/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zxz/CLionProjects/tpce_mysql

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zxz/CLionProjects/tpce_mysql

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2020.2.4/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zxz/CLionProjects/tpce_mysql/CMakeFiles /home/zxz/CLionProjects/tpce_mysql/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zxz/CLionProjects/tpce_mysql/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DBT5_BROKERAGE_HOUSE

# Build rule for target.
DBT5_BROKERAGE_HOUSE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DBT5_BROKERAGE_HOUSE
.PHONY : DBT5_BROKERAGE_HOUSE

# fast build rule for target.
DBT5_BROKERAGE_HOUSE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build
.PHONY : DBT5_BROKERAGE_HOUSE/fast

#=============================================================================
# Target rules for targets named DBT5_DRIVER

# Build rule for target.
DBT5_DRIVER: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DBT5_DRIVER
.PHONY : DBT5_DRIVER

# fast build rule for target.
DBT5_DRIVER/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/build
.PHONY : DBT5_DRIVER/fast

#=============================================================================
# Target rules for targets named DBT5_MARKET_EXCHANGE

# Build rule for target.
DBT5_MARKET_EXCHANGE: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DBT5_MARKET_EXCHANGE
.PHONY : DBT5_MARKET_EXCHANGE

# fast build rule for target.
DBT5_MARKET_EXCHANGE/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build
.PHONY : DBT5_MARKET_EXCHANGE/fast

assi/src/AddressTable.o: assi/src/AddressTable.cpp.o

.PHONY : assi/src/AddressTable.o

# target to build an object file
assi/src/AddressTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/AddressTable.cpp.o
.PHONY : assi/src/AddressTable.cpp.o

assi/src/AddressTable.i: assi/src/AddressTable.cpp.i

.PHONY : assi/src/AddressTable.i

# target to preprocess a source file
assi/src/AddressTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/AddressTable.cpp.i
.PHONY : assi/src/AddressTable.cpp.i

assi/src/AddressTable.s: assi/src/AddressTable.cpp.s

.PHONY : assi/src/AddressTable.s

# target to generate assembly for a file
assi/src/AddressTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/AddressTable.cpp.s
.PHONY : assi/src/AddressTable.cpp.s

assi/src/BaseLogger.o: assi/src/BaseLogger.cpp.o

.PHONY : assi/src/BaseLogger.o

# target to build an object file
assi/src/BaseLogger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/BaseLogger.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/BaseLogger.cpp.o
.PHONY : assi/src/BaseLogger.cpp.o

assi/src/BaseLogger.i: assi/src/BaseLogger.cpp.i

.PHONY : assi/src/BaseLogger.i

# target to preprocess a source file
assi/src/BaseLogger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/BaseLogger.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/BaseLogger.cpp.i
.PHONY : assi/src/BaseLogger.cpp.i

assi/src/BaseLogger.s: assi/src/BaseLogger.cpp.s

.PHONY : assi/src/BaseLogger.s

# target to generate assembly for a file
assi/src/BaseLogger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/BaseLogger.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/BaseLogger.cpp.s
.PHONY : assi/src/BaseLogger.cpp.s

assi/src/CE.o: assi/src/CE.cpp.o

.PHONY : assi/src/CE.o

# target to build an object file
assi/src/CE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CE.cpp.o
.PHONY : assi/src/CE.cpp.o

assi/src/CE.i: assi/src/CE.cpp.i

.PHONY : assi/src/CE.i

# target to preprocess a source file
assi/src/CE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CE.cpp.i
.PHONY : assi/src/CE.cpp.i

assi/src/CE.s: assi/src/CE.cpp.s

.PHONY : assi/src/CE.s

# target to generate assembly for a file
assi/src/CE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CE.cpp.s
.PHONY : assi/src/CE.cpp.s

assi/src/CETxnInputGenerator.o: assi/src/CETxnInputGenerator.cpp.o

.PHONY : assi/src/CETxnInputGenerator.o

# target to build an object file
assi/src/CETxnInputGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CETxnInputGenerator.cpp.o
.PHONY : assi/src/CETxnInputGenerator.cpp.o

assi/src/CETxnInputGenerator.i: assi/src/CETxnInputGenerator.cpp.i

.PHONY : assi/src/CETxnInputGenerator.i

# target to preprocess a source file
assi/src/CETxnInputGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CETxnInputGenerator.cpp.i
.PHONY : assi/src/CETxnInputGenerator.cpp.i

assi/src/CETxnInputGenerator.s: assi/src/CETxnInputGenerator.cpp.s

.PHONY : assi/src/CETxnInputGenerator.s

# target to generate assembly for a file
assi/src/CETxnInputGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CETxnInputGenerator.cpp.s
.PHONY : assi/src/CETxnInputGenerator.cpp.s

assi/src/CETxnMixGenerator.o: assi/src/CETxnMixGenerator.cpp.o

.PHONY : assi/src/CETxnMixGenerator.o

# target to build an object file
assi/src/CETxnMixGenerator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CETxnMixGenerator.cpp.o
.PHONY : assi/src/CETxnMixGenerator.cpp.o

assi/src/CETxnMixGenerator.i: assi/src/CETxnMixGenerator.cpp.i

.PHONY : assi/src/CETxnMixGenerator.i

# target to preprocess a source file
assi/src/CETxnMixGenerator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CETxnMixGenerator.cpp.i
.PHONY : assi/src/CETxnMixGenerator.cpp.i

assi/src/CETxnMixGenerator.s: assi/src/CETxnMixGenerator.cpp.s

.PHONY : assi/src/CETxnMixGenerator.s

# target to generate assembly for a file
assi/src/CETxnMixGenerator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CETxnMixGenerator.cpp.s
.PHONY : assi/src/CETxnMixGenerator.cpp.s

assi/src/CustomerSelection.o: assi/src/CustomerSelection.cpp.o

.PHONY : assi/src/CustomerSelection.o

# target to build an object file
assi/src/CustomerSelection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CustomerSelection.cpp.o
.PHONY : assi/src/CustomerSelection.cpp.o

assi/src/CustomerSelection.i: assi/src/CustomerSelection.cpp.i

.PHONY : assi/src/CustomerSelection.i

# target to preprocess a source file
assi/src/CustomerSelection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CustomerSelection.cpp.i
.PHONY : assi/src/CustomerSelection.cpp.i

assi/src/CustomerSelection.s: assi/src/CustomerSelection.cpp.s

.PHONY : assi/src/CustomerSelection.s

# target to generate assembly for a file
assi/src/CustomerSelection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CustomerSelection.cpp.s
.PHONY : assi/src/CustomerSelection.cpp.s

assi/src/CustomerTable.o: assi/src/CustomerTable.cpp.o

.PHONY : assi/src/CustomerTable.o

# target to build an object file
assi/src/CustomerTable.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CustomerTable.cpp.o
.PHONY : assi/src/CustomerTable.cpp.o

assi/src/CustomerTable.i: assi/src/CustomerTable.cpp.i

.PHONY : assi/src/CustomerTable.i

# target to preprocess a source file
assi/src/CustomerTable.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CustomerTable.cpp.i
.PHONY : assi/src/CustomerTable.cpp.i

assi/src/CustomerTable.s: assi/src/CustomerTable.cpp.s

.PHONY : assi/src/CustomerTable.s

# target to generate assembly for a file
assi/src/CustomerTable.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/CustomerTable.cpp.s
.PHONY : assi/src/CustomerTable.cpp.s

assi/src/DM.o: assi/src/DM.cpp.o

.PHONY : assi/src/DM.o

# target to build an object file
assi/src/DM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/DM.cpp.o
.PHONY : assi/src/DM.cpp.o

assi/src/DM.i: assi/src/DM.cpp.i

.PHONY : assi/src/DM.i

# target to preprocess a source file
assi/src/DM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/DM.cpp.i
.PHONY : assi/src/DM.cpp.i

assi/src/DM.s: assi/src/DM.cpp.s

.PHONY : assi/src/DM.s

# target to generate assembly for a file
assi/src/DM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/DM.cpp.s
.PHONY : assi/src/DM.cpp.s

assi/src/DateTime.o: assi/src/DateTime.cpp.o

.PHONY : assi/src/DateTime.o

# target to build an object file
assi/src/DateTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/assi/src/DateTime.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/DateTime.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/DateTime.cpp.o
.PHONY : assi/src/DateTime.cpp.o

assi/src/DateTime.i: assi/src/DateTime.cpp.i

.PHONY : assi/src/DateTime.i

# target to preprocess a source file
assi/src/DateTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/assi/src/DateTime.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/DateTime.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/DateTime.cpp.i
.PHONY : assi/src/DateTime.cpp.i

assi/src/DateTime.s: assi/src/DateTime.cpp.s

.PHONY : assi/src/DateTime.s

# target to generate assembly for a file
assi/src/DateTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/assi/src/DateTime.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/DateTime.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/DateTime.cpp.s
.PHONY : assi/src/DateTime.cpp.s

assi/src/EGenLogFormatterTab.o: assi/src/EGenLogFormatterTab.cpp.o

.PHONY : assi/src/EGenLogFormatterTab.o

# target to build an object file
assi/src/EGenLogFormatterTab.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/EGenLogFormatterTab.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/EGenLogFormatterTab.cpp.o
.PHONY : assi/src/EGenLogFormatterTab.cpp.o

assi/src/EGenLogFormatterTab.i: assi/src/EGenLogFormatterTab.cpp.i

.PHONY : assi/src/EGenLogFormatterTab.i

# target to preprocess a source file
assi/src/EGenLogFormatterTab.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/EGenLogFormatterTab.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/EGenLogFormatterTab.cpp.i
.PHONY : assi/src/EGenLogFormatterTab.cpp.i

assi/src/EGenLogFormatterTab.s: assi/src/EGenLogFormatterTab.cpp.s

.PHONY : assi/src/EGenLogFormatterTab.s

# target to generate assembly for a file
assi/src/EGenLogFormatterTab.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/EGenLogFormatterTab.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/EGenLogFormatterTab.cpp.s
.PHONY : assi/src/EGenLogFormatterTab.cpp.s

assi/src/EGenVersion.o: assi/src/EGenVersion.cpp.o

.PHONY : assi/src/EGenVersion.o

# target to build an object file
assi/src/EGenVersion.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/EGenVersion.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/EGenVersion.cpp.o
.PHONY : assi/src/EGenVersion.cpp.o

assi/src/EGenVersion.i: assi/src/EGenVersion.cpp.i

.PHONY : assi/src/EGenVersion.i

# target to preprocess a source file
assi/src/EGenVersion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/EGenVersion.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/EGenVersion.cpp.i
.PHONY : assi/src/EGenVersion.cpp.i

assi/src/EGenVersion.s: assi/src/EGenVersion.cpp.s

.PHONY : assi/src/EGenVersion.s

# target to generate assembly for a file
assi/src/EGenVersion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/EGenVersion.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/EGenVersion.cpp.s
.PHONY : assi/src/EGenVersion.cpp.s

assi/src/InputFlatFilesStructure.o: assi/src/InputFlatFilesStructure.cpp.o

.PHONY : assi/src/InputFlatFilesStructure.o

# target to build an object file
assi/src/InputFlatFilesStructure.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/InputFlatFilesStructure.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/InputFlatFilesStructure.cpp.o
.PHONY : assi/src/InputFlatFilesStructure.cpp.o

assi/src/InputFlatFilesStructure.i: assi/src/InputFlatFilesStructure.cpp.i

.PHONY : assi/src/InputFlatFilesStructure.i

# target to preprocess a source file
assi/src/InputFlatFilesStructure.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/InputFlatFilesStructure.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/InputFlatFilesStructure.cpp.i
.PHONY : assi/src/InputFlatFilesStructure.cpp.i

assi/src/InputFlatFilesStructure.s: assi/src/InputFlatFilesStructure.cpp.s

.PHONY : assi/src/InputFlatFilesStructure.s

# target to generate assembly for a file
assi/src/InputFlatFilesStructure.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/InputFlatFilesStructure.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/InputFlatFilesStructure.cpp.s
.PHONY : assi/src/InputFlatFilesStructure.cpp.s

assi/src/MEE.o: assi/src/MEE.cpp.o

.PHONY : assi/src/MEE.o

# target to build an object file
assi/src/MEE.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEE.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEE.cpp.o
.PHONY : assi/src/MEE.cpp.o

assi/src/MEE.i: assi/src/MEE.cpp.i

.PHONY : assi/src/MEE.i

# target to preprocess a source file
assi/src/MEE.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEE.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEE.cpp.i
.PHONY : assi/src/MEE.cpp.i

assi/src/MEE.s: assi/src/MEE.cpp.s

.PHONY : assi/src/MEE.s

# target to generate assembly for a file
assi/src/MEE.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEE.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEE.cpp.s
.PHONY : assi/src/MEE.cpp.s

assi/src/MEEPriceBoard.o: assi/src/MEEPriceBoard.cpp.o

.PHONY : assi/src/MEEPriceBoard.o

# target to build an object file
assi/src/MEEPriceBoard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEEPriceBoard.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEEPriceBoard.cpp.o
.PHONY : assi/src/MEEPriceBoard.cpp.o

assi/src/MEEPriceBoard.i: assi/src/MEEPriceBoard.cpp.i

.PHONY : assi/src/MEEPriceBoard.i

# target to preprocess a source file
assi/src/MEEPriceBoard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEEPriceBoard.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEEPriceBoard.cpp.i
.PHONY : assi/src/MEEPriceBoard.cpp.i

assi/src/MEEPriceBoard.s: assi/src/MEEPriceBoard.cpp.s

.PHONY : assi/src/MEEPriceBoard.s

# target to generate assembly for a file
assi/src/MEEPriceBoard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEEPriceBoard.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEEPriceBoard.cpp.s
.PHONY : assi/src/MEEPriceBoard.cpp.s

assi/src/MEESecurity.o: assi/src/MEESecurity.cpp.o

.PHONY : assi/src/MEESecurity.o

# target to build an object file
assi/src/MEESecurity.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEESecurity.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEESecurity.cpp.o
.PHONY : assi/src/MEESecurity.cpp.o

assi/src/MEESecurity.i: assi/src/MEESecurity.cpp.i

.PHONY : assi/src/MEESecurity.i

# target to preprocess a source file
assi/src/MEESecurity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEESecurity.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEESecurity.cpp.i
.PHONY : assi/src/MEESecurity.cpp.i

assi/src/MEESecurity.s: assi/src/MEESecurity.cpp.s

.PHONY : assi/src/MEESecurity.s

# target to generate assembly for a file
assi/src/MEESecurity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEESecurity.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEESecurity.cpp.s
.PHONY : assi/src/MEESecurity.cpp.s

assi/src/MEETickerTape.o: assi/src/MEETickerTape.cpp.o

.PHONY : assi/src/MEETickerTape.o

# target to build an object file
assi/src/MEETickerTape.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEETickerTape.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEETickerTape.cpp.o
.PHONY : assi/src/MEETickerTape.cpp.o

assi/src/MEETickerTape.i: assi/src/MEETickerTape.cpp.i

.PHONY : assi/src/MEETickerTape.i

# target to preprocess a source file
assi/src/MEETickerTape.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEETickerTape.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEETickerTape.cpp.i
.PHONY : assi/src/MEETickerTape.cpp.i

assi/src/MEETickerTape.s: assi/src/MEETickerTape.cpp.s

.PHONY : assi/src/MEETickerTape.s

# target to generate assembly for a file
assi/src/MEETickerTape.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEETickerTape.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEETickerTape.cpp.s
.PHONY : assi/src/MEETickerTape.cpp.s

assi/src/MEETradingFloor.o: assi/src/MEETradingFloor.cpp.o

.PHONY : assi/src/MEETradingFloor.o

# target to build an object file
assi/src/MEETradingFloor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEETradingFloor.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEETradingFloor.cpp.o
.PHONY : assi/src/MEETradingFloor.cpp.o

assi/src/MEETradingFloor.i: assi/src/MEETradingFloor.cpp.i

.PHONY : assi/src/MEETradingFloor.i

# target to preprocess a source file
assi/src/MEETradingFloor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEETradingFloor.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEETradingFloor.cpp.i
.PHONY : assi/src/MEETradingFloor.cpp.i

assi/src/MEETradingFloor.s: assi/src/MEETradingFloor.cpp.s

.PHONY : assi/src/MEETradingFloor.s

# target to generate assembly for a file
assi/src/MEETradingFloor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/MEETradingFloor.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/MEETradingFloor.cpp.s
.PHONY : assi/src/MEETradingFloor.cpp.s

assi/src/Person.o: assi/src/Person.cpp.o

.PHONY : assi/src/Person.o

# target to build an object file
assi/src/Person.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/Person.cpp.o
.PHONY : assi/src/Person.cpp.o

assi/src/Person.i: assi/src/Person.cpp.i

.PHONY : assi/src/Person.i

# target to preprocess a source file
assi/src/Person.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/Person.cpp.i
.PHONY : assi/src/Person.cpp.i

assi/src/Person.s: assi/src/Person.cpp.s

.PHONY : assi/src/Person.s

# target to generate assembly for a file
assi/src/Person.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/Person.cpp.s
.PHONY : assi/src/Person.cpp.s

assi/src/Random.o: assi/src/Random.cpp.o

.PHONY : assi/src/Random.o

# target to build an object file
assi/src/Random.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/Random.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/Random.cpp.o
.PHONY : assi/src/Random.cpp.o

assi/src/Random.i: assi/src/Random.cpp.i

.PHONY : assi/src/Random.i

# target to preprocess a source file
assi/src/Random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/Random.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/Random.cpp.i
.PHONY : assi/src/Random.cpp.i

assi/src/Random.s: assi/src/Random.cpp.s

.PHONY : assi/src/Random.s

# target to generate assembly for a file
assi/src/Random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/Random.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/Random.cpp.s
.PHONY : assi/src/Random.cpp.s

assi/src/ReadRowFunctions.o: assi/src/ReadRowFunctions.cpp.o

.PHONY : assi/src/ReadRowFunctions.o

# target to build an object file
assi/src/ReadRowFunctions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/ReadRowFunctions.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/ReadRowFunctions.cpp.o
.PHONY : assi/src/ReadRowFunctions.cpp.o

assi/src/ReadRowFunctions.i: assi/src/ReadRowFunctions.cpp.i

.PHONY : assi/src/ReadRowFunctions.i

# target to preprocess a source file
assi/src/ReadRowFunctions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/ReadRowFunctions.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/ReadRowFunctions.cpp.i
.PHONY : assi/src/ReadRowFunctions.cpp.i

assi/src/ReadRowFunctions.s: assi/src/ReadRowFunctions.cpp.s

.PHONY : assi/src/ReadRowFunctions.s

# target to generate assembly for a file
assi/src/ReadRowFunctions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/ReadRowFunctions.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/ReadRowFunctions.cpp.s
.PHONY : assi/src/ReadRowFunctions.cpp.s

assi/src/WheelTime.o: assi/src/WheelTime.cpp.o

.PHONY : assi/src/WheelTime.o

# target to build an object file
assi/src/WheelTime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/WheelTime.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/WheelTime.cpp.o
.PHONY : assi/src/WheelTime.cpp.o

assi/src/WheelTime.i: assi/src/WheelTime.cpp.i

.PHONY : assi/src/WheelTime.i

# target to preprocess a source file
assi/src/WheelTime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/WheelTime.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/WheelTime.cpp.i
.PHONY : assi/src/WheelTime.cpp.i

assi/src/WheelTime.s: assi/src/WheelTime.cpp.s

.PHONY : assi/src/WheelTime.s

# target to generate assembly for a file
assi/src/WheelTime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/WheelTime.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/WheelTime.cpp.s
.PHONY : assi/src/WheelTime.cpp.s

assi/src/error.o: assi/src/error.cpp.o

.PHONY : assi/src/error.o

# target to build an object file
assi/src/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/error.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/error.cpp.o
.PHONY : assi/src/error.cpp.o

assi/src/error.i: assi/src/error.cpp.i

.PHONY : assi/src/error.i

# target to preprocess a source file
assi/src/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/error.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/error.cpp.i
.PHONY : assi/src/error.cpp.i

assi/src/error.s: assi/src/error.cpp.s

.PHONY : assi/src/error.s

# target to generate assembly for a file
assi/src/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/error.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/error.cpp.s
.PHONY : assi/src/error.cpp.s

assi/src/locking.o: assi/src/locking.cpp.o

.PHONY : assi/src/locking.o

# target to build an object file
assi/src/locking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/assi/src/locking.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/locking.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/locking.cpp.o
.PHONY : assi/src/locking.cpp.o

assi/src/locking.i: assi/src/locking.cpp.i

.PHONY : assi/src/locking.i

# target to preprocess a source file
assi/src/locking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/assi/src/locking.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/locking.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/locking.cpp.i
.PHONY : assi/src/locking.cpp.i

assi/src/locking.s: assi/src/locking.cpp.s

.PHONY : assi/src/locking.s

# target to generate assembly for a file
assi/src/locking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/assi/src/locking.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/assi/src/locking.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/assi/src/locking.cpp.s
.PHONY : assi/src/locking.cpp.s

src/BrokerageHouse/BrokerageHouse.o: src/BrokerageHouse/BrokerageHouse.cpp.o

.PHONY : src/BrokerageHouse/BrokerageHouse.o

# target to build an object file
src/BrokerageHouse/BrokerageHouse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/BrokerageHouse/BrokerageHouse.cpp.o
.PHONY : src/BrokerageHouse/BrokerageHouse.cpp.o

src/BrokerageHouse/BrokerageHouse.i: src/BrokerageHouse/BrokerageHouse.cpp.i

.PHONY : src/BrokerageHouse/BrokerageHouse.i

# target to preprocess a source file
src/BrokerageHouse/BrokerageHouse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/BrokerageHouse/BrokerageHouse.cpp.i
.PHONY : src/BrokerageHouse/BrokerageHouse.cpp.i

src/BrokerageHouse/BrokerageHouse.s: src/BrokerageHouse/BrokerageHouse.cpp.s

.PHONY : src/BrokerageHouse/BrokerageHouse.s

# target to generate assembly for a file
src/BrokerageHouse/BrokerageHouse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/BrokerageHouse/BrokerageHouse.cpp.s
.PHONY : src/BrokerageHouse/BrokerageHouse.cpp.s

src/BrokerageHouse/BrokerageHouseMain.o: src/BrokerageHouse/BrokerageHouseMain.cpp.o

.PHONY : src/BrokerageHouse/BrokerageHouseMain.o

# target to build an object file
src/BrokerageHouse/BrokerageHouseMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/BrokerageHouse/BrokerageHouseMain.cpp.o
.PHONY : src/BrokerageHouse/BrokerageHouseMain.cpp.o

src/BrokerageHouse/BrokerageHouseMain.i: src/BrokerageHouse/BrokerageHouseMain.cpp.i

.PHONY : src/BrokerageHouse/BrokerageHouseMain.i

# target to preprocess a source file
src/BrokerageHouse/BrokerageHouseMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/BrokerageHouse/BrokerageHouseMain.cpp.i
.PHONY : src/BrokerageHouse/BrokerageHouseMain.cpp.i

src/BrokerageHouse/BrokerageHouseMain.s: src/BrokerageHouse/BrokerageHouseMain.cpp.s

.PHONY : src/BrokerageHouse/BrokerageHouseMain.s

# target to generate assembly for a file
src/BrokerageHouse/BrokerageHouseMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/BrokerageHouse/BrokerageHouseMain.cpp.s
.PHONY : src/BrokerageHouse/BrokerageHouseMain.cpp.s

src/Customer/Customer.o: src/Customer/Customer.cpp.o

.PHONY : src/Customer/Customer.o

# target to build an object file
src/Customer/Customer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/Customer/Customer.cpp.o
.PHONY : src/Customer/Customer.cpp.o

src/Customer/Customer.i: src/Customer/Customer.cpp.i

.PHONY : src/Customer/Customer.i

# target to preprocess a source file
src/Customer/Customer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/Customer/Customer.cpp.i
.PHONY : src/Customer/Customer.cpp.i

src/Customer/Customer.s: src/Customer/Customer.cpp.s

.PHONY : src/Customer/Customer.s

# target to generate assembly for a file
src/Customer/Customer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/Customer/Customer.cpp.s
.PHONY : src/Customer/Customer.cpp.s

src/Driver/Driver.o: src/Driver/Driver.cpp.o

.PHONY : src/Driver/Driver.o

# target to build an object file
src/Driver/Driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/Driver/Driver.cpp.o
.PHONY : src/Driver/Driver.cpp.o

src/Driver/Driver.i: src/Driver/Driver.cpp.i

.PHONY : src/Driver/Driver.i

# target to preprocess a source file
src/Driver/Driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/Driver/Driver.cpp.i
.PHONY : src/Driver/Driver.cpp.i

src/Driver/Driver.s: src/Driver/Driver.cpp.s

.PHONY : src/Driver/Driver.s

# target to generate assembly for a file
src/Driver/Driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/Driver/Driver.cpp.s
.PHONY : src/Driver/Driver.cpp.s

src/Driver/DriverMain.o: src/Driver/DriverMain.cpp.o

.PHONY : src/Driver/DriverMain.o

# target to build an object file
src/Driver/DriverMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/Driver/DriverMain.cpp.o
.PHONY : src/Driver/DriverMain.cpp.o

src/Driver/DriverMain.i: src/Driver/DriverMain.cpp.i

.PHONY : src/Driver/DriverMain.i

# target to preprocess a source file
src/Driver/DriverMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/Driver/DriverMain.cpp.i
.PHONY : src/Driver/DriverMain.cpp.i

src/Driver/DriverMain.s: src/Driver/DriverMain.cpp.s

.PHONY : src/Driver/DriverMain.s

# target to generate assembly for a file
src/Driver/DriverMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/Driver/DriverMain.cpp.s
.PHONY : src/Driver/DriverMain.cpp.s

src/MarketExchange/MarketExchange.o: src/MarketExchange/MarketExchange.cpp.o

.PHONY : src/MarketExchange/MarketExchange.o

# target to build an object file
src/MarketExchange/MarketExchange.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/MarketExchange/MarketExchange.cpp.o
.PHONY : src/MarketExchange/MarketExchange.cpp.o

src/MarketExchange/MarketExchange.i: src/MarketExchange/MarketExchange.cpp.i

.PHONY : src/MarketExchange/MarketExchange.i

# target to preprocess a source file
src/MarketExchange/MarketExchange.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/MarketExchange/MarketExchange.cpp.i
.PHONY : src/MarketExchange/MarketExchange.cpp.i

src/MarketExchange/MarketExchange.s: src/MarketExchange/MarketExchange.cpp.s

.PHONY : src/MarketExchange/MarketExchange.s

# target to generate assembly for a file
src/MarketExchange/MarketExchange.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/MarketExchange/MarketExchange.cpp.s
.PHONY : src/MarketExchange/MarketExchange.cpp.s

src/MarketExchange/MarketExchangeMain.o: src/MarketExchange/MarketExchangeMain.cpp.o

.PHONY : src/MarketExchange/MarketExchangeMain.o

# target to build an object file
src/MarketExchange/MarketExchangeMain.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/MarketExchange/MarketExchangeMain.cpp.o
.PHONY : src/MarketExchange/MarketExchangeMain.cpp.o

src/MarketExchange/MarketExchangeMain.i: src/MarketExchange/MarketExchangeMain.cpp.i

.PHONY : src/MarketExchange/MarketExchangeMain.i

# target to preprocess a source file
src/MarketExchange/MarketExchangeMain.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/MarketExchange/MarketExchangeMain.cpp.i
.PHONY : src/MarketExchange/MarketExchangeMain.cpp.i

src/MarketExchange/MarketExchangeMain.s: src/MarketExchange/MarketExchangeMain.cpp.s

.PHONY : src/MarketExchange/MarketExchangeMain.s

# target to generate assembly for a file
src/MarketExchange/MarketExchangeMain.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/MarketExchange/MarketExchangeMain.cpp.s
.PHONY : src/MarketExchange/MarketExchangeMain.cpp.s

src/interfaces/BaseInterface.o: src/interfaces/BaseInterface.cpp.o

.PHONY : src/interfaces/BaseInterface.o

# target to build an object file
src/interfaces/BaseInterface.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/BaseInterface.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/interfaces/BaseInterface.cpp.o
.PHONY : src/interfaces/BaseInterface.cpp.o

src/interfaces/BaseInterface.i: src/interfaces/BaseInterface.cpp.i

.PHONY : src/interfaces/BaseInterface.i

# target to preprocess a source file
src/interfaces/BaseInterface.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/BaseInterface.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/interfaces/BaseInterface.cpp.i
.PHONY : src/interfaces/BaseInterface.cpp.i

src/interfaces/BaseInterface.s: src/interfaces/BaseInterface.cpp.s

.PHONY : src/interfaces/BaseInterface.s

# target to generate assembly for a file
src/interfaces/BaseInterface.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/BaseInterface.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/interfaces/BaseInterface.cpp.s
.PHONY : src/interfaces/BaseInterface.cpp.s

src/interfaces/CESUT.o: src/interfaces/CESUT.cpp.o

.PHONY : src/interfaces/CESUT.o

# target to build an object file
src/interfaces/CESUT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/CESUT.cpp.o
.PHONY : src/interfaces/CESUT.cpp.o

src/interfaces/CESUT.i: src/interfaces/CESUT.cpp.i

.PHONY : src/interfaces/CESUT.i

# target to preprocess a source file
src/interfaces/CESUT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/CESUT.cpp.i
.PHONY : src/interfaces/CESUT.cpp.i

src/interfaces/CESUT.s: src/interfaces/CESUT.cpp.s

.PHONY : src/interfaces/CESUT.s

# target to generate assembly for a file
src/interfaces/CESUT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/CESUT.cpp.s
.PHONY : src/interfaces/CESUT.cpp.s

src/interfaces/CSocket.o: src/interfaces/CSocket.cpp.o

.PHONY : src/interfaces/CSocket.o

# target to build an object file
src/interfaces/CSocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/interfaces/CSocket.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/CSocket.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/interfaces/CSocket.cpp.o
.PHONY : src/interfaces/CSocket.cpp.o

src/interfaces/CSocket.i: src/interfaces/CSocket.cpp.i

.PHONY : src/interfaces/CSocket.i

# target to preprocess a source file
src/interfaces/CSocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/interfaces/CSocket.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/CSocket.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/interfaces/CSocket.cpp.i
.PHONY : src/interfaces/CSocket.cpp.i

src/interfaces/CSocket.s: src/interfaces/CSocket.cpp.s

.PHONY : src/interfaces/CSocket.s

# target to generate assembly for a file
src/interfaces/CSocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/interfaces/CSocket.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/CSocket.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/interfaces/CSocket.cpp.s
.PHONY : src/interfaces/CSocket.cpp.s

src/interfaces/DMSUT.o: src/interfaces/DMSUT.cpp.o

.PHONY : src/interfaces/DMSUT.o

# target to build an object file
src/interfaces/DMSUT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/DMSUT.cpp.o
.PHONY : src/interfaces/DMSUT.cpp.o

src/interfaces/DMSUT.i: src/interfaces/DMSUT.cpp.i

.PHONY : src/interfaces/DMSUT.i

# target to preprocess a source file
src/interfaces/DMSUT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/DMSUT.cpp.i
.PHONY : src/interfaces/DMSUT.cpp.i

src/interfaces/DMSUT.s: src/interfaces/DMSUT.cpp.s

.PHONY : src/interfaces/DMSUT.s

# target to generate assembly for a file
src/interfaces/DMSUT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_DRIVER.dir/build.make CMakeFiles/DBT5_DRIVER.dir/src/interfaces/DMSUT.cpp.s
.PHONY : src/interfaces/DMSUT.cpp.s

src/interfaces/MEESUT.o: src/interfaces/MEESUT.cpp.o

.PHONY : src/interfaces/MEESUT.o

# target to build an object file
src/interfaces/MEESUT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/interfaces/MEESUT.cpp.o
.PHONY : src/interfaces/MEESUT.cpp.o

src/interfaces/MEESUT.i: src/interfaces/MEESUT.cpp.i

.PHONY : src/interfaces/MEESUT.i

# target to preprocess a source file
src/interfaces/MEESUT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/interfaces/MEESUT.cpp.i
.PHONY : src/interfaces/MEESUT.cpp.i

src/interfaces/MEESUT.s: src/interfaces/MEESUT.cpp.s

.PHONY : src/interfaces/MEESUT.s

# target to generate assembly for a file
src/interfaces/MEESUT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_MARKET_EXCHANGE.dir/build.make CMakeFiles/DBT5_MARKET_EXCHANGE.dir/src/interfaces/MEESUT.cpp.s
.PHONY : src/interfaces/MEESUT.cpp.s

src/interfaces/TxnHarnessSendToMarket.o: src/interfaces/TxnHarnessSendToMarket.cpp.o

.PHONY : src/interfaces/TxnHarnessSendToMarket.o

# target to build an object file
src/interfaces/TxnHarnessSendToMarket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/interfaces/TxnHarnessSendToMarket.cpp.o
.PHONY : src/interfaces/TxnHarnessSendToMarket.cpp.o

src/interfaces/TxnHarnessSendToMarket.i: src/interfaces/TxnHarnessSendToMarket.cpp.i

.PHONY : src/interfaces/TxnHarnessSendToMarket.i

# target to preprocess a source file
src/interfaces/TxnHarnessSendToMarket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/interfaces/TxnHarnessSendToMarket.cpp.i
.PHONY : src/interfaces/TxnHarnessSendToMarket.cpp.i

src/interfaces/TxnHarnessSendToMarket.s: src/interfaces/TxnHarnessSendToMarket.cpp.s

.PHONY : src/interfaces/TxnHarnessSendToMarket.s

# target to generate assembly for a file
src/interfaces/TxnHarnessSendToMarket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/interfaces/TxnHarnessSendToMarket.cpp.s
.PHONY : src/interfaces/TxnHarnessSendToMarket.cpp.s

src/transactions/BrokerVolumeDB.o: src/transactions/BrokerVolumeDB.cpp.o

.PHONY : src/transactions/BrokerVolumeDB.o

# target to build an object file
src/transactions/BrokerVolumeDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/BrokerVolumeDB.cpp.o
.PHONY : src/transactions/BrokerVolumeDB.cpp.o

src/transactions/BrokerVolumeDB.i: src/transactions/BrokerVolumeDB.cpp.i

.PHONY : src/transactions/BrokerVolumeDB.i

# target to preprocess a source file
src/transactions/BrokerVolumeDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/BrokerVolumeDB.cpp.i
.PHONY : src/transactions/BrokerVolumeDB.cpp.i

src/transactions/BrokerVolumeDB.s: src/transactions/BrokerVolumeDB.cpp.s

.PHONY : src/transactions/BrokerVolumeDB.s

# target to generate assembly for a file
src/transactions/BrokerVolumeDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/BrokerVolumeDB.cpp.s
.PHONY : src/transactions/BrokerVolumeDB.cpp.s

src/transactions/CustomerPositionDB.o: src/transactions/CustomerPositionDB.cpp.o

.PHONY : src/transactions/CustomerPositionDB.o

# target to build an object file
src/transactions/CustomerPositionDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/CustomerPositionDB.cpp.o
.PHONY : src/transactions/CustomerPositionDB.cpp.o

src/transactions/CustomerPositionDB.i: src/transactions/CustomerPositionDB.cpp.i

.PHONY : src/transactions/CustomerPositionDB.i

# target to preprocess a source file
src/transactions/CustomerPositionDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/CustomerPositionDB.cpp.i
.PHONY : src/transactions/CustomerPositionDB.cpp.i

src/transactions/CustomerPositionDB.s: src/transactions/CustomerPositionDB.cpp.s

.PHONY : src/transactions/CustomerPositionDB.s

# target to generate assembly for a file
src/transactions/CustomerPositionDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/CustomerPositionDB.cpp.s
.PHONY : src/transactions/CustomerPositionDB.cpp.s

src/transactions/DBConnection.o: src/transactions/DBConnection.cpp.o

.PHONY : src/transactions/DBConnection.o

# target to build an object file
src/transactions/DBConnection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/DBConnection.cpp.o
.PHONY : src/transactions/DBConnection.cpp.o

src/transactions/DBConnection.i: src/transactions/DBConnection.cpp.i

.PHONY : src/transactions/DBConnection.i

# target to preprocess a source file
src/transactions/DBConnection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/DBConnection.cpp.i
.PHONY : src/transactions/DBConnection.cpp.i

src/transactions/DBConnection.s: src/transactions/DBConnection.cpp.s

.PHONY : src/transactions/DBConnection.s

# target to generate assembly for a file
src/transactions/DBConnection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/DBConnection.cpp.s
.PHONY : src/transactions/DBConnection.cpp.s

src/transactions/DataMaintenanceDB.o: src/transactions/DataMaintenanceDB.cpp.o

.PHONY : src/transactions/DataMaintenanceDB.o

# target to build an object file
src/transactions/DataMaintenanceDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/DataMaintenanceDB.cpp.o
.PHONY : src/transactions/DataMaintenanceDB.cpp.o

src/transactions/DataMaintenanceDB.i: src/transactions/DataMaintenanceDB.cpp.i

.PHONY : src/transactions/DataMaintenanceDB.i

# target to preprocess a source file
src/transactions/DataMaintenanceDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/DataMaintenanceDB.cpp.i
.PHONY : src/transactions/DataMaintenanceDB.cpp.i

src/transactions/DataMaintenanceDB.s: src/transactions/DataMaintenanceDB.cpp.s

.PHONY : src/transactions/DataMaintenanceDB.s

# target to generate assembly for a file
src/transactions/DataMaintenanceDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/DataMaintenanceDB.cpp.s
.PHONY : src/transactions/DataMaintenanceDB.cpp.s

src/transactions/MarketFeedDB.o: src/transactions/MarketFeedDB.cpp.o

.PHONY : src/transactions/MarketFeedDB.o

# target to build an object file
src/transactions/MarketFeedDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/MarketFeedDB.cpp.o
.PHONY : src/transactions/MarketFeedDB.cpp.o

src/transactions/MarketFeedDB.i: src/transactions/MarketFeedDB.cpp.i

.PHONY : src/transactions/MarketFeedDB.i

# target to preprocess a source file
src/transactions/MarketFeedDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/MarketFeedDB.cpp.i
.PHONY : src/transactions/MarketFeedDB.cpp.i

src/transactions/MarketFeedDB.s: src/transactions/MarketFeedDB.cpp.s

.PHONY : src/transactions/MarketFeedDB.s

# target to generate assembly for a file
src/transactions/MarketFeedDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/MarketFeedDB.cpp.s
.PHONY : src/transactions/MarketFeedDB.cpp.s

src/transactions/MarketWatchDB.o: src/transactions/MarketWatchDB.cpp.o

.PHONY : src/transactions/MarketWatchDB.o

# target to build an object file
src/transactions/MarketWatchDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/MarketWatchDB.cpp.o
.PHONY : src/transactions/MarketWatchDB.cpp.o

src/transactions/MarketWatchDB.i: src/transactions/MarketWatchDB.cpp.i

.PHONY : src/transactions/MarketWatchDB.i

# target to preprocess a source file
src/transactions/MarketWatchDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/MarketWatchDB.cpp.i
.PHONY : src/transactions/MarketWatchDB.cpp.i

src/transactions/MarketWatchDB.s: src/transactions/MarketWatchDB.cpp.s

.PHONY : src/transactions/MarketWatchDB.s

# target to generate assembly for a file
src/transactions/MarketWatchDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/MarketWatchDB.cpp.s
.PHONY : src/transactions/MarketWatchDB.cpp.s

src/transactions/SecurityDetailDB.o: src/transactions/SecurityDetailDB.cpp.o

.PHONY : src/transactions/SecurityDetailDB.o

# target to build an object file
src/transactions/SecurityDetailDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/SecurityDetailDB.cpp.o
.PHONY : src/transactions/SecurityDetailDB.cpp.o

src/transactions/SecurityDetailDB.i: src/transactions/SecurityDetailDB.cpp.i

.PHONY : src/transactions/SecurityDetailDB.i

# target to preprocess a source file
src/transactions/SecurityDetailDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/SecurityDetailDB.cpp.i
.PHONY : src/transactions/SecurityDetailDB.cpp.i

src/transactions/SecurityDetailDB.s: src/transactions/SecurityDetailDB.cpp.s

.PHONY : src/transactions/SecurityDetailDB.s

# target to generate assembly for a file
src/transactions/SecurityDetailDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/SecurityDetailDB.cpp.s
.PHONY : src/transactions/SecurityDetailDB.cpp.s

src/transactions/TradeCleanupDB.o: src/transactions/TradeCleanupDB.cpp.o

.PHONY : src/transactions/TradeCleanupDB.o

# target to build an object file
src/transactions/TradeCleanupDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeCleanupDB.cpp.o
.PHONY : src/transactions/TradeCleanupDB.cpp.o

src/transactions/TradeCleanupDB.i: src/transactions/TradeCleanupDB.cpp.i

.PHONY : src/transactions/TradeCleanupDB.i

# target to preprocess a source file
src/transactions/TradeCleanupDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeCleanupDB.cpp.i
.PHONY : src/transactions/TradeCleanupDB.cpp.i

src/transactions/TradeCleanupDB.s: src/transactions/TradeCleanupDB.cpp.s

.PHONY : src/transactions/TradeCleanupDB.s

# target to generate assembly for a file
src/transactions/TradeCleanupDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeCleanupDB.cpp.s
.PHONY : src/transactions/TradeCleanupDB.cpp.s

src/transactions/TradeLookupDB.o: src/transactions/TradeLookupDB.cpp.o

.PHONY : src/transactions/TradeLookupDB.o

# target to build an object file
src/transactions/TradeLookupDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeLookupDB.cpp.o
.PHONY : src/transactions/TradeLookupDB.cpp.o

src/transactions/TradeLookupDB.i: src/transactions/TradeLookupDB.cpp.i

.PHONY : src/transactions/TradeLookupDB.i

# target to preprocess a source file
src/transactions/TradeLookupDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeLookupDB.cpp.i
.PHONY : src/transactions/TradeLookupDB.cpp.i

src/transactions/TradeLookupDB.s: src/transactions/TradeLookupDB.cpp.s

.PHONY : src/transactions/TradeLookupDB.s

# target to generate assembly for a file
src/transactions/TradeLookupDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeLookupDB.cpp.s
.PHONY : src/transactions/TradeLookupDB.cpp.s

src/transactions/TradeOrderDB.o: src/transactions/TradeOrderDB.cpp.o

.PHONY : src/transactions/TradeOrderDB.o

# target to build an object file
src/transactions/TradeOrderDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeOrderDB.cpp.o
.PHONY : src/transactions/TradeOrderDB.cpp.o

src/transactions/TradeOrderDB.i: src/transactions/TradeOrderDB.cpp.i

.PHONY : src/transactions/TradeOrderDB.i

# target to preprocess a source file
src/transactions/TradeOrderDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeOrderDB.cpp.i
.PHONY : src/transactions/TradeOrderDB.cpp.i

src/transactions/TradeOrderDB.s: src/transactions/TradeOrderDB.cpp.s

.PHONY : src/transactions/TradeOrderDB.s

# target to generate assembly for a file
src/transactions/TradeOrderDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeOrderDB.cpp.s
.PHONY : src/transactions/TradeOrderDB.cpp.s

src/transactions/TradeResultDB.o: src/transactions/TradeResultDB.cpp.o

.PHONY : src/transactions/TradeResultDB.o

# target to build an object file
src/transactions/TradeResultDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeResultDB.cpp.o
.PHONY : src/transactions/TradeResultDB.cpp.o

src/transactions/TradeResultDB.i: src/transactions/TradeResultDB.cpp.i

.PHONY : src/transactions/TradeResultDB.i

# target to preprocess a source file
src/transactions/TradeResultDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeResultDB.cpp.i
.PHONY : src/transactions/TradeResultDB.cpp.i

src/transactions/TradeResultDB.s: src/transactions/TradeResultDB.cpp.s

.PHONY : src/transactions/TradeResultDB.s

# target to generate assembly for a file
src/transactions/TradeResultDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeResultDB.cpp.s
.PHONY : src/transactions/TradeResultDB.cpp.s

src/transactions/TradeStatusDB.o: src/transactions/TradeStatusDB.cpp.o

.PHONY : src/transactions/TradeStatusDB.o

# target to build an object file
src/transactions/TradeStatusDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeStatusDB.cpp.o
.PHONY : src/transactions/TradeStatusDB.cpp.o

src/transactions/TradeStatusDB.i: src/transactions/TradeStatusDB.cpp.i

.PHONY : src/transactions/TradeStatusDB.i

# target to preprocess a source file
src/transactions/TradeStatusDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeStatusDB.cpp.i
.PHONY : src/transactions/TradeStatusDB.cpp.i

src/transactions/TradeStatusDB.s: src/transactions/TradeStatusDB.cpp.s

.PHONY : src/transactions/TradeStatusDB.s

# target to generate assembly for a file
src/transactions/TradeStatusDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeStatusDB.cpp.s
.PHONY : src/transactions/TradeStatusDB.cpp.s

src/transactions/TradeUpdateDB.o: src/transactions/TradeUpdateDB.cpp.o

.PHONY : src/transactions/TradeUpdateDB.o

# target to build an object file
src/transactions/TradeUpdateDB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeUpdateDB.cpp.o
.PHONY : src/transactions/TradeUpdateDB.cpp.o

src/transactions/TradeUpdateDB.i: src/transactions/TradeUpdateDB.cpp.i

.PHONY : src/transactions/TradeUpdateDB.i

# target to preprocess a source file
src/transactions/TradeUpdateDB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeUpdateDB.cpp.i
.PHONY : src/transactions/TradeUpdateDB.cpp.i

src/transactions/TradeUpdateDB.s: src/transactions/TradeUpdateDB.cpp.s

.PHONY : src/transactions/TradeUpdateDB.s

# target to generate assembly for a file
src/transactions/TradeUpdateDB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TradeUpdateDB.cpp.s
.PHONY : src/transactions/TradeUpdateDB.cpp.s

src/transactions/TxnDBBase.o: src/transactions/TxnDBBase.cpp.o

.PHONY : src/transactions/TxnDBBase.o

# target to build an object file
src/transactions/TxnDBBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TxnDBBase.cpp.o
.PHONY : src/transactions/TxnDBBase.cpp.o

src/transactions/TxnDBBase.i: src/transactions/TxnDBBase.cpp.i

.PHONY : src/transactions/TxnDBBase.i

# target to preprocess a source file
src/transactions/TxnDBBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TxnDBBase.cpp.i
.PHONY : src/transactions/TxnDBBase.cpp.i

src/transactions/TxnDBBase.s: src/transactions/TxnDBBase.cpp.s

.PHONY : src/transactions/TxnDBBase.s

# target to generate assembly for a file
src/transactions/TxnDBBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/build.make CMakeFiles/DBT5_BROKERAGE_HOUSE.dir/src/transactions/TxnDBBase.cpp.s
.PHONY : src/transactions/TxnDBBase.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... DBT5_BROKERAGE_HOUSE"
	@echo "... DBT5_DRIVER"
	@echo "... DBT5_MARKET_EXCHANGE"
	@echo "... assi/src/AddressTable.o"
	@echo "... assi/src/AddressTable.i"
	@echo "... assi/src/AddressTable.s"
	@echo "... assi/src/BaseLogger.o"
	@echo "... assi/src/BaseLogger.i"
	@echo "... assi/src/BaseLogger.s"
	@echo "... assi/src/CE.o"
	@echo "... assi/src/CE.i"
	@echo "... assi/src/CE.s"
	@echo "... assi/src/CETxnInputGenerator.o"
	@echo "... assi/src/CETxnInputGenerator.i"
	@echo "... assi/src/CETxnInputGenerator.s"
	@echo "... assi/src/CETxnMixGenerator.o"
	@echo "... assi/src/CETxnMixGenerator.i"
	@echo "... assi/src/CETxnMixGenerator.s"
	@echo "... assi/src/CustomerSelection.o"
	@echo "... assi/src/CustomerSelection.i"
	@echo "... assi/src/CustomerSelection.s"
	@echo "... assi/src/CustomerTable.o"
	@echo "... assi/src/CustomerTable.i"
	@echo "... assi/src/CustomerTable.s"
	@echo "... assi/src/DM.o"
	@echo "... assi/src/DM.i"
	@echo "... assi/src/DM.s"
	@echo "... assi/src/DateTime.o"
	@echo "... assi/src/DateTime.i"
	@echo "... assi/src/DateTime.s"
	@echo "... assi/src/EGenLogFormatterTab.o"
	@echo "... assi/src/EGenLogFormatterTab.i"
	@echo "... assi/src/EGenLogFormatterTab.s"
	@echo "... assi/src/EGenVersion.o"
	@echo "... assi/src/EGenVersion.i"
	@echo "... assi/src/EGenVersion.s"
	@echo "... assi/src/InputFlatFilesStructure.o"
	@echo "... assi/src/InputFlatFilesStructure.i"
	@echo "... assi/src/InputFlatFilesStructure.s"
	@echo "... assi/src/MEE.o"
	@echo "... assi/src/MEE.i"
	@echo "... assi/src/MEE.s"
	@echo "... assi/src/MEEPriceBoard.o"
	@echo "... assi/src/MEEPriceBoard.i"
	@echo "... assi/src/MEEPriceBoard.s"
	@echo "... assi/src/MEESecurity.o"
	@echo "... assi/src/MEESecurity.i"
	@echo "... assi/src/MEESecurity.s"
	@echo "... assi/src/MEETickerTape.o"
	@echo "... assi/src/MEETickerTape.i"
	@echo "... assi/src/MEETickerTape.s"
	@echo "... assi/src/MEETradingFloor.o"
	@echo "... assi/src/MEETradingFloor.i"
	@echo "... assi/src/MEETradingFloor.s"
	@echo "... assi/src/Person.o"
	@echo "... assi/src/Person.i"
	@echo "... assi/src/Person.s"
	@echo "... assi/src/Random.o"
	@echo "... assi/src/Random.i"
	@echo "... assi/src/Random.s"
	@echo "... assi/src/ReadRowFunctions.o"
	@echo "... assi/src/ReadRowFunctions.i"
	@echo "... assi/src/ReadRowFunctions.s"
	@echo "... assi/src/WheelTime.o"
	@echo "... assi/src/WheelTime.i"
	@echo "... assi/src/WheelTime.s"
	@echo "... assi/src/error.o"
	@echo "... assi/src/error.i"
	@echo "... assi/src/error.s"
	@echo "... assi/src/locking.o"
	@echo "... assi/src/locking.i"
	@echo "... assi/src/locking.s"
	@echo "... src/BrokerageHouse/BrokerageHouse.o"
	@echo "... src/BrokerageHouse/BrokerageHouse.i"
	@echo "... src/BrokerageHouse/BrokerageHouse.s"
	@echo "... src/BrokerageHouse/BrokerageHouseMain.o"
	@echo "... src/BrokerageHouse/BrokerageHouseMain.i"
	@echo "... src/BrokerageHouse/BrokerageHouseMain.s"
	@echo "... src/Customer/Customer.o"
	@echo "... src/Customer/Customer.i"
	@echo "... src/Customer/Customer.s"
	@echo "... src/Driver/Driver.o"
	@echo "... src/Driver/Driver.i"
	@echo "... src/Driver/Driver.s"
	@echo "... src/Driver/DriverMain.o"
	@echo "... src/Driver/DriverMain.i"
	@echo "... src/Driver/DriverMain.s"
	@echo "... src/MarketExchange/MarketExchange.o"
	@echo "... src/MarketExchange/MarketExchange.i"
	@echo "... src/MarketExchange/MarketExchange.s"
	@echo "... src/MarketExchange/MarketExchangeMain.o"
	@echo "... src/MarketExchange/MarketExchangeMain.i"
	@echo "... src/MarketExchange/MarketExchangeMain.s"
	@echo "... src/interfaces/BaseInterface.o"
	@echo "... src/interfaces/BaseInterface.i"
	@echo "... src/interfaces/BaseInterface.s"
	@echo "... src/interfaces/CESUT.o"
	@echo "... src/interfaces/CESUT.i"
	@echo "... src/interfaces/CESUT.s"
	@echo "... src/interfaces/CSocket.o"
	@echo "... src/interfaces/CSocket.i"
	@echo "... src/interfaces/CSocket.s"
	@echo "... src/interfaces/DMSUT.o"
	@echo "... src/interfaces/DMSUT.i"
	@echo "... src/interfaces/DMSUT.s"
	@echo "... src/interfaces/MEESUT.o"
	@echo "... src/interfaces/MEESUT.i"
	@echo "... src/interfaces/MEESUT.s"
	@echo "... src/interfaces/TxnHarnessSendToMarket.o"
	@echo "... src/interfaces/TxnHarnessSendToMarket.i"
	@echo "... src/interfaces/TxnHarnessSendToMarket.s"
	@echo "... src/transactions/BrokerVolumeDB.o"
	@echo "... src/transactions/BrokerVolumeDB.i"
	@echo "... src/transactions/BrokerVolumeDB.s"
	@echo "... src/transactions/CustomerPositionDB.o"
	@echo "... src/transactions/CustomerPositionDB.i"
	@echo "... src/transactions/CustomerPositionDB.s"
	@echo "... src/transactions/DBConnection.o"
	@echo "... src/transactions/DBConnection.i"
	@echo "... src/transactions/DBConnection.s"
	@echo "... src/transactions/DataMaintenanceDB.o"
	@echo "... src/transactions/DataMaintenanceDB.i"
	@echo "... src/transactions/DataMaintenanceDB.s"
	@echo "... src/transactions/MarketFeedDB.o"
	@echo "... src/transactions/MarketFeedDB.i"
	@echo "... src/transactions/MarketFeedDB.s"
	@echo "... src/transactions/MarketWatchDB.o"
	@echo "... src/transactions/MarketWatchDB.i"
	@echo "... src/transactions/MarketWatchDB.s"
	@echo "... src/transactions/SecurityDetailDB.o"
	@echo "... src/transactions/SecurityDetailDB.i"
	@echo "... src/transactions/SecurityDetailDB.s"
	@echo "... src/transactions/TradeCleanupDB.o"
	@echo "... src/transactions/TradeCleanupDB.i"
	@echo "... src/transactions/TradeCleanupDB.s"
	@echo "... src/transactions/TradeLookupDB.o"
	@echo "... src/transactions/TradeLookupDB.i"
	@echo "... src/transactions/TradeLookupDB.s"
	@echo "... src/transactions/TradeOrderDB.o"
	@echo "... src/transactions/TradeOrderDB.i"
	@echo "... src/transactions/TradeOrderDB.s"
	@echo "... src/transactions/TradeResultDB.o"
	@echo "... src/transactions/TradeResultDB.i"
	@echo "... src/transactions/TradeResultDB.s"
	@echo "... src/transactions/TradeStatusDB.o"
	@echo "... src/transactions/TradeStatusDB.i"
	@echo "... src/transactions/TradeStatusDB.s"
	@echo "... src/transactions/TradeUpdateDB.o"
	@echo "... src/transactions/TradeUpdateDB.i"
	@echo "... src/transactions/TradeUpdateDB.s"
	@echo "... src/transactions/TxnDBBase.o"
	@echo "... src/transactions/TxnDBBase.i"
	@echo "... src/transactions/TxnDBBase.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

